version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: orgolink-auth-postgres
    environment:
      POSTGRES_DB: orgolink_auth
      POSTGRES_USER: orgolink
      POSTGRES_PASSWORD: orgolink123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - orgolink-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orgolink -d orgolink_auth"]
      interval: 30s
      timeout: 10s
      retries: 3

  orgolink-auth:
    build: .
    container_name: orgolink-auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orgolink_auth
      - SPRING_DATASOURCE_USERNAME=orgolink
      - SPRING_DATASOURCE_PASSWORD=orgolink123
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
    ports:
      - "8080:8080"
    networks:
      - orgolink-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: orgolink-auth-nginx
    depends_on:
      - orgolink-auth
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - orgolink-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: orgolink-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orgolink-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  orgolink-network:
    driver: bridge
